apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata: 
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "cadocruz/hello-go:0.2.2"

          resources:
            requests:
              cpu: "0.3"
              memory: 20Mi
            limits:
              cpu: "0.3"
              memory: 25Mi  
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
        
          volumeMounts:
            - mountPath: "/myfamily"
              name: config

      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"
